# Generated by Django 5.2.4 on 2025-07-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='contactperson',
            table='contact_person',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contract',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='opportunity',
            table='opportunity',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='support_ticket',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
